version: '3.8'
services:
  trading-bot:
    container_name: java-trading-bot
    build:
      context: ./
      dockerfile: Dockerfile
    image: trading-bot:latest
    ports:
      - 9999:9999
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge